### PR TITLE
Add supplementary R scoring files

### PR DESCRIPTION
**Pull request by earcanal**

### CODE REVIEW

**Comment by vsoch** [comment]
@IanEisenberg what are your thoughts on here as well?

**Comment by vsoch** [comment]
Let me know when you are ready / done here as well!

**Comment by earcanal** [comment]
Done!

**Review by vsoch — APPROVED** [review]

**Comment by vsoch** [comment]
@earcanal I approved, but I'm concerned that you are making this one survey different from all of the others by removing the welcome screen message. Perhaps we should be consistent?

**Comment by earcanal** [comment]
If consistency is important, I would suggest removing the welcome screen from all surveys. I recall that they confused some participants ("yes, just press any key to start the survey") which (marginally) increased the duration of an experiment.

**Comment by vsoch** [comment]
Then that should be done separately, and probably discussed with others first. I’m not sure I agree it’s best to remove.

**Comment by vsoch** [comment]
A lot of times the survey computer is left briefly or waiting for a participant, in which case the questions should not be on the screen. Knowing that a participant went beyond that screen also is an indicator that they started the survey. You lose that information when you remove it. So I’m not sure that I agree that it’s universally bad to add an extra click and few seconds.

**Comment by earcanal** [comment]
OK. It's not a problem for me if you want to revert that commit for consistency.

**Comment by vsoch** [comment]
@earcanal since this is your PR and you have the code locally (and it's harder for me to do) could you please make the reversion?

**Comment by earcanal** [comment]
> @earcanal since this is your PR and you have the code locally (and it's harder for me to do) could you please make the reversion?

No problem.

**Review by vsoch — APPROVED** [review]
Thank you @earcanal !

**Pull request merged**
